"""renamed relationship fields

Revision ID: 015e248f2535
Revises: 3a6e3c93a73c
Create Date: 2023-06-13 21:18:53.288245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '015e248f2535'
down_revision = '3a6e3c93a73c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
