"""migrations

Revision ID: 39cf9236b4af
Revises: c831deb83eeb
Create Date: 2023-08-03 03:11:59.072477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39cf9236b4af'
down_revision = 'c831deb83eeb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
