"""added xamm wallets model

Revision ID: a5ff7723dfd3
Revises: 015e248f2535
Create Date: 2023-07-29 09:00:47.486389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5ff7723dfd3'
down_revision = '015e248f2535'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
