"""added tf immediate

Revision ID: c831deb83eeb
Revises: a5ff7723dfd3
Create Date: 2023-07-29 09:20:26.476494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c831deb83eeb'
down_revision = 'a5ff7723dfd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
